name: test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env:
  TZ: Asia/Shanghai
  
jobs:

  test:
    strategy:
      matrix:
        vm-os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.vm-os }}
    env:
      GO111MODULE: on
      GOPROXY: https://goproxy.cn
    steps:
      - name: Setup go
        uses: actions/setup-go@v4
        with:
          go-version: '>=1.16.0'
      - name: Install dependencies
        uses: actions/checkout@v3

      - name: Create test coverage file
        run: go test -coverprofile='coverage.txt' -covermode=atomic

      - name: Upload coverage file to codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{secrets.CODECOV_TOKEN}}
